import React, { useEffect, useState } from 'react'
import { Card, Form, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    )
  }

  return (
    <h2 className='mt-6 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');

  return (
    <section className='max-w-8xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-black text-[33px]'>The Community Showcase</h1>
        <p className='mt-2 text-[#666e75] text-[15px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>
      <div className='mt-18'>
      </div>

      <div className='mt-11'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-sans text-[#666e75] text-xl mb-3'>
                Showing results for <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-5 sm:grid-cols-4 xs:grid-cols-3 grid-cols-2 gap-5'>
              {searchText ? (
                <RenderCards
                  data={[]}
                  title='No search results found'
                />
              ) : (
                <RenderCards
                  data={[]}
                  title='No posts found'
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>


  )
}

export default Home
